sudo: required
services:
    - docker

before_install:
    - docker build -t v2dev7/docker-react -f Dockerfile.dev .

#when we just run below command without coverage, we wont command prompt. Thats
# the reason we got incluse the -- --coverage option
script:
    -  docker run v2dev7/docker-react npm run test -- --coverage

