sudo: required
services:
    - docker

before_install:
    - docker build -t v2dev7/docker-react -f Dockerfile.dev .

#when we just run below command without coverage, we wont command prompt. Thats
# the reason we got incluse the -- --coverage option

script:
    -  docker run -e CI=true v2dev7/docker-react npm run test -- --coverage

deploy: 
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "Docker-React"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-904847677487"    
    bucket_path: "Docker-React"
    on:     
      branch: master
    acess_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
